const arr = [
    [
        'Timestamp',
        'A) Course, Semester, Section, Shift',
        'B) Choose your Class Coordinator',
        'C) Quality of Interaction with Class Coordinator',
        'D) Name of the BM Faculty',
        'How satisfied were you with BM Faculty ?  \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding [Subject knowledge]',
        'How satisfied were you with BM Faculty ?  \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding [Communication Skills]',
        'How satisfied were you with BM Faculty ?  \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding [Interactive Approach & Clear doubts]',
        'How satisfied were you with BM Faculty ?  \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding [Covers all the topic of the Syllabus]',
        'How satisfied were you with BM Faculty ?  \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding [Punctuality in taking classes]',
        'How satisfied were you with BM Faculty ?  \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding [Control over the class]',
        'E) Name of the BC Faculty',
        'How satisfied were you with BC Faculty ?          \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding [Subject knowledge]',
        'How satisfied were you with BC Faculty ?          \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding [Communication Skills]',
        'How satisfied were you with BC Faculty ?          \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding [Interactive Approach & Clear doubts]',
        'How satisfied were you with BC Faculty ?          \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding [Covers all the topic of the Syllabus]',
        'How satisfied were you with BC Faculty ?          \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding [Punctuality in taking classes]',
        'How satisfied were you with BC Faculty ?          \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding [Control over the class]',
        'F) Name of the CA Faculty',
        'How satisfied were you with CA Faculty ?                        \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding   [Subject knowledge]',
        'How satisfied were you with CA Faculty ?                        \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding   [Communication Skills]',
        'How satisfied were you with CA Faculty ?                        \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding   [Interactive Approach & Clear doubts]',
        'How satisfied were you with CA Faculty ?                        \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding   [Covers all the topic of the Syllabus]',
        'How satisfied were you with CA Faculty ?                        \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding   [Punctuality in taking classes]',
        'How satisfied were you with CA Faculty ?                        \n1= Poor, 2= Fair, 3= Good, 4= Very Good, 5=Outstanding   [Control over the class]',
        'G) Name of the POI Faculty',
    ],
    [
        '1/5/2023 22:50:33',
        'BBA (B & I) II (M)',
        'Dr. Parul Deshwal',
        'Mentor & Motivator',
        'Ms. Aanchal Tehlan',
        '1',
        '2',
        '2',
        '1',
        '2',
        '2',
        'Dr. Abhyendra Singh',
        '5',
        '5',
        '5',
        '5',
        '5',
        '5',
        'Dr. Parul Deshwal',
        '2',
        '4',
        '5',
        '5',
        '3',
        '3',
        'Dr. Parul Deshwal',
    ],
    [
        '1/5/2023 22:52:05',
        'BBA (B & I) II (M)',
        'Dr. Parul Deshwal',
        'Supportive',
        'Dr. Vijay Dahiya',
        '5',
        '4',
        '5',
        '4',
        '5',
        '4',
        'Ms. Arti Malik',
        '5',
        '4',
        '5',
        '3',
        '3',
        '2',
        'Dr. Parul Deshwal',
        '2',
        '3',
        '1',
        '3',
        '4',
        '4',
        'Dr. Parul Deshwal',
    ],
    [
        '1/5/2023 22:52:46',
        'BBA (B & I) II (M)',
        'Dr. Vijay Dahiya',
        'Supportive',
        'Dr. Vijay Dahiya',
        '4',
        '4',
        '3',
        '4',
        '3',
        '5',
        'Dr. Abhyendra Singh',
        '5',
        '4',
        '4',
        '5',
        '4',
        '5',
        'Dr. Parul Deshwal',
        '5',
        '4',
        '4',
        '5',
        '4',
        '5',
        'Ms. Harshita Gupta',
    ],
    [
        '1/5/2023 22:52:48',
        'BBA (B & I) II (M)',
        'Dr. Vijay Dahiya',
        'Mentor & Motivator',
        'Ms. Aanchal Tehlan',
        '1',
        '1',
        '1',
        '2',
        '1',
        '1',
        'Ms. Arti Malik',
        '1',
        '3',
        '2',
        '3',
        '3',
        '5',
        'Dr. Rajeshwari Malik',
        '1',
        '2',
        '4',
        '1',
        '4',
        '5',
        'Dr. Parul Deshwal',
    ],
    [
        '1/6/2023 3:22:41',
        'BBA (B & I) II (E)',
        'Dr. Vijay Dahiya',
        'Supportive',
        'Ms. Aanchal Tehlan',
        '3',
        '2',
        '2',
        '3',
        '3',
        '3',
        'Dr. Abhyendra Singh',
        '2',
        '2',
        '3',
        '2',
        '2',
        '3',
        'Dr. Parul Deshwal',
        '2',
        '3',
        '2',
        '3',
        '3',
        '2',
        'Ms. Harshita Gupta',
    ],
];


